language: generic
sudo: require
services:
  - docker

before_install:
  - docker build -t docker_course -f Dockerfile.dev .

script:
  - docker run -e CI=true docker_course npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker_course"
  env: "Dockercourse-env"
  bucket_name: "elasticbeanstalk-eu-west-2-195667116120"
  bucket_path: "docker_course"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
