language: generic
sudo: require
services:
  - docker

before_install:
  - docker build -t docker_course -f Dockerfile.dev .

script:
  - docker run -e CI=true docker_course npm run test -- --coverage
